version: "3"

services:
  postgres:
    image: postgres
    container_name: postgres_lab
    ports:
      - 5439:5432
    environment:
      POSTGRES_DB: lab
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/dump.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "lab" ]
      interval: 30s
      timeout: 60s
      retries: 5
